---
title: "20210323-p8158_hw6_jsg2145"
author: "Jared Garfinkel"
date: "3/23/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(psych)
library(lavaan)
library(semPlot)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# read in data

```{r}
data = read_csv("./data/SEM for uwcb.csv") %>% 
  janitor::clean_names()
```

```{r}
skimr::skim(data)
head(data)
```

```{r}
df = data %>% 
  mutate(across(.fns = as.numeric))
```

```{r}
names(df)
```


# SEM

```{r}
model <- ' 
  # latent variable definitions
     outuwcb =~ diet_yr + uwcb_yr
     bmi_sf ~ bodysat + outuwcb + wtteas
     bmi_sf ~ wtteas
     bodysat ~ outuwcb
     wtteas =~ teasewt + fam_wt + bodysat + outuwcb
     wtteas ~ outuwcb + bodysat
'
#      bmi_sf ~ outuwcb + bodysat + wtteas
#      
#      bodysat ~ outuwcb
#      wtteas ~ teasewt + fam_wt + outuwcb + bodysat + bmi_sf
# '
```

```{r, eval = FALSE}
model.fit <- sem(model, data = df, sample.cov=TRUE, missing = "ML")
```

```{r, eval = FALSE}
semPaths(model.fit)
```



